### ISSUE TITLE
std::logic_error: Mat::init(): requested size is not compatible with column vector layout

### ISSUE THREAD

**Issue by XintongHe** [poad42/ARIMA_CPP#1]
Hi,
I tried to run your code, but keep getting the error: std::logic_error: Mat::init(): requested size is not compatible with column vector layout
I didn't change anything, just make first and the ./main
The full log is: ADF test results:
Test statistic: -61.3412
P-value: 0
The series is stationary
n = 74934
libc++abi: terminating due to uncaught exception of type std::logic_error: Mat::init(): requested size is not compatible with column vector layout
zsh: abort      ./main

Do you have any idea why is it?
Thank you very much
Best
Xintong He

**Comment by poad42** [comment]
Hello,
 I fixed the error now, looks I made a mistake in PACF function call. However I also have to emphasize that I still haven't implemented APIs for autoregressive (AR) or moving average (MA) terms(p,q). But thanks for bringing this up.
